src/Yizhou.Website/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yizhou.Website.Models;
using Yizhou.Api;

namespace Yizhou.Website.Controllers
{
    public class LoginController : BaseController
    {
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SignIn(string account, string password, bool remember, string returnUrl)
        {
            ControllerResultModel resultModel = new ControllerResultModel();
            try
            {
                string token = WebHelper.AuthenticationService.SignIn(account, password, Request.UserHostAddress);
                resultModel.Add("data", this.Url.Action("Redirect", new { url = returnUrl, token = token, remember = remember }));
            }
            catch (Exception ex)
            {
                resultModel.result = false;
                resultModel.message = ex.Message;
                WebHelper.Logger.Error(ex.Message, ex);
            }
            return Json(resultModel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SignOut()
        {
            WebHelper.AuthenticationService.SignOut(WebHelper.CurrentUserToken);
            return this.RedirectToAction("Index");
        }

        public ActionResult Redirect(string url, string token, bool remember)
        {
            if (string.IsNullOrEmpty(url))
            {
                url = this.Url.Action("Index", "Dingdan");
            }

            WebHelper.SetCurrentUserToken(token, remember);
            return this.Redirect(url);
        }
    }
}

src/Yizhou.Website/Controllers/ScriptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Yizhou.Website.Controllers
{
    public class ScriptController : Controller
    {

        public ActionResult Index()
        {
            bool hasCaiwuQuanxian = WebHelper.HasCaiwuQuanxian;
            string hasCaiwuQuanxianScript = string.Format("$.hasCaiwuQuanxian = {0};", hasCaiwuQuanxian.ToString().ToLower());

            return this.JavaScript(hasCaiwuQuanxianScript);
        }
    }
}

src/Yizhou.Website/Views/Shared/UserInfoMoidfyDialog.cshtml
<div class="modal fade" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">修改个人信息</h3>
            </div>
            <form class="form-horizontal">
                <div class="modal-body"> 
                    <div class="form-group">
                        <label class="control-label" style="width: 100px" >姓名<span style="color: Red">*</span></label>
                        <div class="col-8" >
                            <input type="text" class="form-control webui-textbox" name="name" data-required="true"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" style="width: 100px" >Email</label>
                        <div class="col-8" >
                            <input type="text"  class="form-control webui-textbox" name="email" data-pattern="@Html.Raw(@"^[\w-]+(\.[\w-]+)*@[\w-]+(\.[\w-]+)+$")"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" style="width: 100px" >旧密码</label>
                        <div class="col-8" >
                            <input type="password" class="form-control webui-textbox"  name="oldPassword" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" style="width: 100px" >新密码</label>
                        <div class="col-8" >
                            <input type="password" class="form-control webui-textbox"  name="newPassword"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" style="width: 100px" >新密码确认</label>
                        <div class="col-8" >
                            <input type="password" class="form-control webui-textbox"  name="confirmNewPassword"/>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary btnOk" type="submit">确定</button>
                    <button class="btn btn-default" type="button" data-dismiss="modal" aria-hidden="true" >关闭</button>
                </div>
            </form>
        </div>
    </div>
</div>

src/Yizhou.Website/Views/Shared/_Layout.cshtml
@using Yizhou.Website;
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link type="text/css" href='@this.Url.Content("~/css/smoothness/jquery-ui-1.8.23.custom.css")' rel="stylesheet" />
	<link type="text/css" href="@this.Url.Content("~/css/smoothness/jquery-ui-tree.css")" rel="stylesheet" />
    <link type="text/css" href="@this.Url.Content("~/css/webui.css")" rel="stylesheet" />
	<link type="text/css" href='@this.Url.Content("~/css/default.css")' rel="stylesheet" />
	<script type="text/javascript" src='@this.Url.Content("~/js/jquery-1.8.0.min.js")'></script>
	<script type="text/javascript" src='@this.Url.Content("~/js/jquery-ui-1.8.23.custom.min.js")'></script>
	<script type="text/javascript" src='@this.Url.Content("~/js/json.js")'></script>
	<script type="text/javascript" src='@this.Url.Content("~/js/bootstrap.min.js")'></script>
    <script type="text/javascript" src='@this.Url.Content("~/js/webui.js?" + WebHelper.Version)'></script>
	<script type="text/javascript" src="@this.Url.Content("~/js/jquery.ui.pager.js")"></script>
	<script type="text/javascript" src='@this.Url.Content("~/js/jquery-extend.js")'></script>
	<script type="text/javascript" src='@this.Url.Content("~/js/jquery-validate.js")'></script>
	<script type="text/javascript" src='@this.Url.Content("~/js/userInfoMoidfyDialog.js")'></script>
	<script type="text/javascript" src='@this.Url.Action("Index", "Script")'></script>
    <script language="javascript" type="text/javascript">
        $.baseUrl = "@this.Url.Content("~/")";
    </script>
</head>

<body style="padding-top: 60px;">
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">客户信息管理</a>
        </div>
          @{
              string DingdanMenuClass = this.ViewBag.topMenu == "Dingdan" ? "class='active'" : "";
              string KehuDanganMenuClass = this.ViewBag.topMenu == "Kehu" ? "class='active'" : "";
              string DingdanMingxiMenuClass = this.ViewBag.topMenu == "DingdanMingxi" ? "class='active'" : "";
              string ShoukuanMenuClass = this.ViewBag.topMenu == "Shoukuan" ? "class='active'" : "";
              string ChanpinMenuClass = this.ViewBag.topMenu == "Chanpin" ? "class='active'" : "";
        }
        <ul class="nav navbar-nav">
            @if (WebHelper.HasDingdanGuanliQuanxian)
            {
            <li @this.Html.Raw(DingdanMenuClass)><a href="@this.Url.Action("Index", "Dingdan")" >订单管理</a></li>
            <li @this.Html.Raw(KehuDanganMenuClass)><a href="@this.Url.Action("Index", "Kehu")" >客户管理</a></li>
            }
            <li @this.Html.Raw(DingdanMingxiMenuClass)><a href="@this.Url.Action("Index", "DingdanMingxi")" >订单明细</a></li>
            @if (WebHelper.HasDingdanGuanliQuanxian)
            {
            <li @this.Html.Raw(ShoukuanMenuClass)><a href="@this.Url.Action("Index", "Shoukuan")" >收款明细</a></li>
            <li @this.Html.Raw(ChanpinMenuClass)><a href="@this.Url.Action("Index", "Chanpin")" >产品管理</a></li>
            }
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a id="linkCurrentUserInfo" href="#" class="navbar-link">@WebHelper.CurrentUserInfo.Name</a></li>
            <li><a href="@this.Url.Action("SignOut", "Login")" class="navbar-link">退出</a></li>
        </ul>
      </div>
    </div>
    <div class="container-fluid">
        @RenderBody()
    </div>
    <div id="userInfoMoidfyDialog">
        @{this.Html.RenderPartial("UserInfoMoidfyDialog");}
    </div>
</body>
</html>
<script type="text/javascript">
    var userInfoMoidfyDialog = $("#userInfoMoidfyDialog").userInfoMoidfyDialog();
    $("#linkCurrentUserInfo").click(function () {
        userInfoMoidfyDialog.userInfoMoidfyDialog("modify");
        return false;
    });
</script>